---

- name: fetch script results from loadgens
  hosts: loadgen
  become: yes
  become_user: root
  tasks:
    - name: validate vars
      fail:
        msg: "{{ item }} must be defined!"
      when: lookup('vars', item) is undefined
      loop:
        - emqx_script_result_file

    - name: fetch
      fetch:
        src: "/tmp/{{ emqx_script_result_file }}"
        dest: "./tmp/data/{{ emqx_script_result_file }}/{{ inventory_hostname_short }}"
        flat: yes

- name: test
  hosts: localhost
  tasks:
    - name: compress
      archive:
        path:
          - './tmp/data/{{ emqx_script_result_file }}/*'
        dest: "./tmp/data/{{ emqx_script_result_file }}.tar.bz2"
        remove: yes
        format: bz2

...
